name: Actualizar Datos Shapefile

on:
  schedule:
    # Ejecutar a las 11 PM UTC (6 PM Perú)
    - cron: '0 23 * * *'
  workflow_dispatch: # Permite ejecución manual

jobs:
  actualizar-shapefiles:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v4  # Actualizado a v4
      
    - name: Configurar Node.js
      uses: actions/setup-node@v4  # Actualizado a v4
      with:
        node-version: '18'
        
    - name: Instalar dependencias
      run: npm install adm-zip fs-extra node-fetch shapefile
      
    - name: Ejecutar script de actualización
      run: node scripts/actualizar-shapefiles.js
      
    - name: Forzar adición de archivos ignorados y commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # Forzar la adición de la carpeta data aunque esté en .gitignore
        git add -f data/
        git diff --quiet && git diff --staged --quiet || git commit -m "Actualización automática de shapefiles $(date +'%d%m%y')"
        git push