name: Actualizar Datos

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Actualizado a v4
      - uses: actions/setup-node@v4  # Actualizado a v4
        with:
          node-version: '18'
      - run: npm install adm-zip fs-extra node-fetch shapefile
      - run: node scripts/actualizar-shapefiles.js
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # FORZAR la adición de archivos aunque estén en .gitignore
          git add -f data/
          git diff --quiet && git diff --staged --quiet || git commit -m "Actualización automática $(date +'%d%m%y')"
          git pushn automática de shapefiles $(date +'%d%m%y')"
        git push
